- git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm
- shell: git checkout `git describe --abbrev=0 --tags`
  args:
    chdir: ~/.nvm
- name: install node v{{ node_version }}
  shell: . ~/.nvm/nvm.sh && nvm install {{ node_version }}
- shell: . ~/.nvm/nvm.sh && nvm alias default node
