- name: install vim
  yum: name=vim
- name: install git
  yum: name=git
- name: install jq
  yum: name=jq
- yum: name=bzip2
- yum: name=unzip
- yum: name=gcc
- yum: name=memcached
- yum: name=openssl-devel
- yum: name=zlib-devel
- yum: name=readline-devel
- yum: name=sqlite-devel
- name: install epel
  yum: name=epel-release
- name: install redis
  yum: name=redis
- name: download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: ~/
- name: install pip
  shell: python ~/get-pip.py
- name: remove get-pip.py
  file:
    path: ~/get-pip.py
    state: absent
- name: install pexpect
  pip: name=pexpect
